### ISSUE TITLE
How do you train and test for rotated shape?

### ISSUE THREAD

**Issue by chenerg** [NolenChen/3DStructurePoints#2]
I have noticed `num_of_transform`, but I don't konw the value for training and test.

**Comment by NolenChen** [comment]
We use PCA based data augmentation strategy to narrow down the rotation space.
You can set num_of_transform to 3 or 4 in training, empirically it does not matter a lot and depends on your GPU memory.
 In the testing stage, the shape should also be aligned with PCA. I will update the testing code for the rotated shapes then.
Thanks for your interest.

**Comment by jimmy15923** [comment]
Hi @NolenChen!
How do you perform the shape alignment with PCA? I have set num_of_tranform to 4 in training and I want to test it on the real-world dataset (each object is not well-aligned). How should I perform the alignment? Thank you!

https://github.com/NolenChen/3DStructurePoints/blob/master/evaluate/evaluate_corres_accuracy.py#L84
