### ISSUE TITLE
 how to evaluate the correspondence accuracy

### ISSUE THREAD

**Issue by Botranz** [NolenChen/3DStructurePoints#6]
how to compute the correspondence accuracy on bhcp dataset, will you release your code soon?

**Comment by Botranz** [comment]
Besides, how did you get the results of the compared method in Fig.5, and what does the ratio(0.00, 0.05, 0.10) in x-axis means? Thanks.

**Comment by NolenChen** [comment]
Thank you for your interest, we will release our evaluation code soon. The 'correspondence accuracy' is described in the [paper ](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/41463.pdf) that proposed the bhcp data set.  
Fig 5 in our paper illustrates the fraction of correspondences predicted correctly (y-axis) for a given Euclidean error threshold (x-axis).
For some methods (LMVCNN,EdgeNet, ShapeUnicode) we use the data provided in their papers. For the 'Critical Point', it is a network property originally discussed in [PointNet](https://arxiv.org/abs/1612.00593), we train the network for classification on the bhcp data set and then evaluate the correspondence accuracy with the learnt critical points on the testing set.
For the encoder-decoder architectures (like atlasnetV2, pointcapsule) we trained their network directly on the bhcp data set.

**Comment by Liu-Ze** [comment]
> Thank you for your interest, we will release our evaluation code soon. The 'correspondence accuracy' is described in the [paper ](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/41463.pdf) that proposed the bhcp data set.
> Fig 5 in our paper illustrates the fraction of correspondences predicted correctly (y-axis) for a given Euclidean error threshold (x-axis).
> For some methods (LMVCNN,EdgeNet, ShapeUnicode) we use the data provided in their papers. For the 'Critical Point', it is a network property originally discussed in [PointNet](https://arxiv.org/abs/1612.00593), we train the network for classification on the bhcp data set and then evaluate the correspondence accuracy with the learnt critical points on the testing set.
> For the encoder-decoder architectures (like atlasnetV2, pointcapsule) we trained their network directly on the bhcp data set.

Thanks! This helps me a lot. Looking forward to your code release.

**Comment by Botranz** [comment]
Thanks a lot! This helps me a lot. Looking forward to your code release.
