### ISSUE TITLE
some question about the requirements.txt

### ISSUE THREAD

**Issue by WangZhouTao** [NolenChen/3DStructurePoints#7]
thanks for your good works!
I try to install the requirements.txt, but I get a error.
`ERROR: Command errored out with exit status 128: git clone -q git://github.com/erikwijmans/etw_pytorch_utils.git /tmp/pip-install-a1tec1br/etw-pytorch-utils Check the logs for full command output.`
is the author deleted the project? Can you fix this problem?
look forward to your reply.

**Comment by NolenChen** [comment]
You are right, the repository was closed.  You may have a try with those forked repositories instead:
https://github.com/chenzhutian/etw_pytorch_utils/network/members
I will test and update my project later.

**Comment by WangZhouTao** [comment]
thank you for your reply.
